import { TypographyOptions } from "@mui/material/styles/createTypography";

const fontConstant = ["Inter", "sans-serif"].join(",");
export const typography: TypographyOptions = {
  htmlFontSize: 16,
  fontFamily: fontConstant,
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: {
    fontFamily: fontConstant,
    fontWeight: 300,
    fontSize: "96px",
    lineHeight: "112px",
    letterSpacing: "-1.5px",
  },
  h2: {
    fontFamily: fontConstant,
    fontWeight: 300,
    fontSize: "60px",
    lineHeight: "120%",
    letterSpacing: "-0.5px",
  },
  h3: {
    fontFamily: fontConstant,
    fontWeight: 400,
    fontSize: "48px",
    lineHeight: "116.7%",
    letterSpacing: "0",
  },
  h4: {
    fontFamily: fontConstant,
    fontWeight: 400,
    fontSize: "34px",
    lineHeight: "123.5%",
    letterSpacing: "-1.25px",
  },
  h5: {
    fontFamily: fontConstant,
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "30px",
    letterSpacing: "-0.85px",
  },
  h6: {
    fontFamily: fontConstant,
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "28px",
    letterSpacing: "-0.5px",
  },
  subtitle1: {
    fontFamily: fontConstant,
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "26px",
    letterSpacing: "-0.35px",
  },
  subtitle2: {
    fontFamily: fontConstant,
    fontWeight: 500,
    fontSize: "15px",
    lineHeight: "18px",
    letterSpacing: "-0.35px",
  },
  body1: {
    fontFamily: fontConstant,
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    letterSpacing: "-0.25px",
  },
  body2: {
    fontFamily: fontConstant,
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "-0.15px",
  },
  button: {
    fontFamily: fontConstant,
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "24px",
    letterSpacing: "-0.2px",
    textTransform: "capitalize",
  },
  caption: {
    fontFamily: fontConstant,
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "18px",
    letterSpacing: "-0.15px",
  },
  overline: {
    fontFamily: fontConstant,
    fontWeight: 500,
    fontSize: "11px",
    lineHeight: "12px",
    letterSpacing: "0.75px",
    textTransform: "uppercase",
  },
};
